/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package SupermarketManagement;

import com.itextpdf.text.Document;
import com.itextpdf.text.FontFactory;
import com.itextpdf.text.Paragraph;
import com.itextpdf.text.pdf.PdfPCell;
import com.itextpdf.text.pdf.PdfPTable;
import com.itextpdf.text.pdf.PdfWriter;
import java.awt.Font;
import java.io.File;
import java.io.FileOutputStream;
import javax.swing.plaf.basic.BasicInternalFrameUI;
import java.sql.*;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author user
 */
public class viewProducts extends javax.swing.JInternalFrame {

    /**
     * Creates new form adminDashboard
     */
    public viewProducts() {
        initComponents();
        loadTable();
        this.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        BasicInternalFrameUI b = (BasicInternalFrameUI) this.getUI();
        b.setNorthPane(null);
    }
    PreparedStatement pst;
    Connection con;
    ResultSet rs;
    private String filepath;

    private void loadTable() {
        DefaultTableModel dft = (DefaultTableModel) jTable1.getModel();
        dft.setRowCount(0);
        try {
            con = database.connectDB();
            pst = con.prepareStatement("select * from productss");
            rs = pst.executeQuery();
            while (rs.next()) {
                dft.addRow(new Object[]{
                    rs.getString("idd"),
                    rs.getString("name"),
                    rs.getString("ppu"),
                    rs.getString("qty")

                });
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/product details ani.gif"))); // NOI18N

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(389, 389, 389)
                .addComponent(jLabel4)
                .addContainerGap(399, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(53, 53, 53)
                .addComponent(jLabel4)
                .addContainerGap(52, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(19, 6, 1080, 170));

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Name", "Price", "Quantity"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 1050, 350));

        jButton1.setBackground(new java.awt.Color(0, 0, 0));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/print.png"))); // NOI18N
        jButton1.setText("Print");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 600, 160, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1117, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try {
            DateTimeFormatter dt = DateTimeFormatter.ofPattern("dd-MM-yyyy");
            LocalDateTime now = LocalDateTime.now();
            String date = dt.format(now);
            con = database.connectDB();
            String query7 = "select * from productss";
            pst = con.prepareStatement(query7);
            rs = pst.executeQuery();

            JFileChooser chooser = new JFileChooser();
            chooser.setSelectedFile(new File("List of Products" + "" + ".pdf"));
            int chooseDialog = chooser.showSaveDialog(null);
            if (chooseDialog == JFileChooser.APPROVE_OPTION) {
                filepath = chooser.getSelectedFile().getPath();
            }
            Document mydocument = new Document();
            PdfWriter.getInstance(mydocument, new FileOutputStream(filepath));
            PdfPTable table = new PdfPTable(4);
            mydocument.open();
            float[] columnWidth = new float[]{7, 7, 7, 7};
            table.setWidths(columnWidth);
            table.setWidthPercentage(100);
            table.setWidthPercentage(100);
            mydocument.add(new Paragraph("                SUPERMARKET MANAGEMENT SYSTEM", FontFactory.getFont(FontFactory.TIMES_BOLDITALIC, 20, Font.ITALIC)));
            mydocument.add(new Paragraph(" "));
            mydocument.add(new Paragraph("                                         LIST OF PRODUCTS", FontFactory.getFont(FontFactory.TIMES_BOLD, 17, Font.PLAIN)));
            mydocument.add(new Paragraph(" "));
            table.addCell(new PdfPCell(new Paragraph("Product ID", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph("Product Name", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph("No. of Units", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLD))));
            table.addCell(new PdfPCell(new Paragraph("Price per Unit", FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.BOLD))));

            while (rs.next()) {
                table.addCell(new PdfPCell(new Paragraph(rs.getString("idd"), FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.PLAIN))));
                table.addCell(new PdfPCell(new Paragraph(rs.getString("name"), FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.PLAIN))));
                table.addCell(new PdfPCell(new Paragraph(rs.getString("qty"), FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.PLAIN))));
                table.addCell(new PdfPCell(new Paragraph(rs.getString("ppu"), FontFactory.getFont(FontFactory.TIMES_ROMAN, 12, Font.PLAIN))));
            }
            mydocument.add(table);
            mydocument.add(new Paragraph(" "));
            mydocument.add(new Paragraph(date, FontFactory.getFont(FontFactory.TIMES_ITALIC, 10, Font.PLAIN)));
            mydocument.close();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        } finally {
            try {
                pst.close();
                rs.close();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, e);
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
